packages:
  - apps/api
  - apps/admin-web
  - apps/staff-mobile
  - packages/*
  - infrastructure/*
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
